module.exports = {
  EMAIL_ALREADY_REGISTERED: "Email deja inregistrat",
  SERVER_ERROR: "Eroare de server",
  INVALID_LOGIN: "Date de autentificare invalide",
  LOGIN_SUCCESS: "Autentificare reusita",
  ORDER_REGISTERED: "Order registered successfully.",
  ORDER_SAVE_ERROR: "Error saving order.",
  INVALID_TABLE_ID: "Table ID is invalid.",
  ORDERS_READ_ERROR: "Error reading orders.",
  STATUS_REQUIRED: "New status is required.",
  ORDER_NOT_FOUND: "Order not found.",
  STATUS_UPDATED: "Status updated successfully.",
  ORDER_HIDE_ERROR: "Error hiding order.",
  ORDER_HIDDEN: "Order was hidden from dashboard.",
  INVALID_ORDER_ID: "Invalid order ID.",
  TABLE_NUMBER_REQUIRED: "Table number is required.",
  WAITER_ALREADY_CALLED: "There is already an active request for this table.",
  WAITER_CALLED: "Waiter has been called.",
  WAITER_ERROR: "Error calling waiter.",
  NO_ORDERS_TO_PAY: "No unpaid orders for this table.",
  ALL_ORDERS_PAID: "All orders have been paid.",
  PAYMENT_PROCESS_ERROR: "Error processing payment.",
  PAYMENT_SUCCESS: "Payment processed",
  PAYMENT_ORDER_NOT_FOUND: "Order not found",
  BUZZ_STATUS_ERROR: "Error checking BUZZ requests.",
  STATS_GENERATION_ERROR: "Error generating statistics.",
  SERVER_RUNNING: "Server running",
  CORS_NOT_ALLOWED: "CORS not allowed",
  MONGO_CONNECTED: "Connected to MongoDB!"
};
